# -*- coding: utf-8 -*-
"""12_manejo_cadenas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RCFmBb17LMRZaG1RWmpY-Epetmc6-OGg

# Manejo de cadenas de caracteres
"""

cadena = 'En un lugar de La Mancha'

"""Método **replace**: reemplazar subcadenas"""

resultado = cadena.replace('a','@')
print(resultado)

"""Método **swapcase**: invierte mayúsculas y minúsculas

---


"""

resultado = cadena.swapcase()
print(resultado)

"""Método **capitalize**: Convierte la primera letra del str en mayúsculas y el resto en minúsculas"""

resultado = cadena.capitalize()
print(resultado)

"""Método **title**: Convierte la primera letra de cada palatra del str en mayúsculas y el resto en minúsculas"""

resultado = cadena.title()
print(resultado)

"""Método **count**: cuenta el número de veces que aparece una subcadena un texto. Si no encuentra la subcadena devuelve 0."""

resultado = cadena.count(' ')
print(resultado)

"""Método **index**: obtiene la posición de una subcadena en un str. Si no encuentra la subcadena provoca un errro de ejecución del tipo ValueError."""

resultado = cadena.index('an')
print(resultado)

"""Método **startswith**: indica si empieza o no por una determina subcadena."""

resultado = cadena.startswith('En un')
print(resultado)
resultado = cadena.startswith('Hace mucho tiempo...')
print(resultado)

"""Método **endswith**: indica si la cadena termina o no por una determinada subcadena."""

resultado = cadena.endswith('hola, mi nombre es José')
print(resultado)
resultado = cadena.endswith('Mancha')
print(resultado)

"""Médodo **find**: busca la primera aparición de una subcadena una cadena. Devuelve la posición donde la encuentra o -1 si no."""

resultado = cadena.find('an')
print(resultado)

"""Método **isdecimal**: verifica si todos los dígitos son decimales (devuelve True o False)"""

es_decimal = cadena.isdecimal()
print(es_decimal) # False
es_decimal = '12345'.isdecimal()
print(es_decimal) # True
es_decimal = '123.45'.isdecimal()
print(es_decimal) # False

"""Métodos **isdigit** y **isnumeric**: isdigit comprueba si contiene dígitos numéricos e isnumeric si contiene expresiones numéricas"""

texto_1 = "1234"
texto_2 = "12r4"
texto_3 = "0b10101"
texto_4 = "10.3"
print(texto_1.isdigit()) # True
print(texto_2.isdigit()) # False
print(texto_3.isdigit()) # False
print(texto_4.isdigit()) # False
print(texto_1.isnumeric()) # True
print(texto_2.isnumeric()) # False
print(texto_3.isnumeric()) # False
print(texto_4.isnumeric()) # False

"""Métodos **islower**, **isupper** y **isspace**: comprueba si una cadena está completamente escrita en minúsculas, mayúsculas o contiene únicamente espacios. Los métodos islower e isupper sólo afectan a los caracteres alfabéticos."""

print(cadena.islower()) # False
print(cadena.isupper()) # False
print(cadena.isspace()) # False
print('soy una cadena'.islower()) # True
print('SOY UNA CADENA'.isupper()) # True
print('         '.isspace()) # True

"""Métodos **upper** y **lower**: devuelve una copia de la cadena con los caracteres alfabéticos convertidos a mayúsculas y minúsculas respectivamente."""

print(cadena.upper())
print(cadena.lower())

"""Métodos **split** y **splitline**: split proporciona una lista con los strings que la componen utilizando como separador el espacio (por defecto) u otra cadena; splitline proporciona una lista en la que cada elemento es un string con el contenido de cada línea del string original."""

tokens = cadena.split()
print(tokens) # ['En', 'un', 'lugar', 'de', 'La', 'Mancha']

texto = """Línea 1
Línea 2
Línea 3
"""
lineas = texto.splitlines()
print(lineas) # ['Línea 1', 'Línea 2', 'Línea 3']

"""Método **join**: une elementos de una colección en una cadena utilizando un separador."""

coleccion = ('Tomate', 'Cebolla', 'Pimiento', 'Aceite', 'Agua', 'Vinagre', 'Sal')
''.join(coleccion) # TomateCebollaPimientoAceiteAguaVinagreSal
'***'.join(coleccion) # Tomate***Cebolla***Pimiento***Aceite***Agua***Vinagre***Sal

"""Técnica de **slicing**: permite obtener una subcadena de caracteres mediante la indicación de posiciones."""

print(cadena) # En un lugar de La Mancha
print(cadena[1:7]) # n un l -> Entre el carácter 1 y 7
print(cadena[:7]) # En un l -> Entre el carácter 0 y 7
print(cadena[5:]) #  lugar de La Mancha -> Entre el 5 y el último
print(cadena[:]) # En un lugar de La Mancha -> Entre el 0 y el último
print(cadena[-3:]) # cha -> Los 3 últimos
print(cadena[:-3]) # En un lugar de La Man -> Entre el 0 y el -3
print(cadena[::3]) # EuladLMc -> Todos tomados cada 3 caracteres
print(cadena[::-2]) # aca Le au un -> Todos tomados cada -2 caracteres (empezando por el final)

"""Añadir **comillas** a una cadena de caracteres"""

'Me dijo "te odio" y se quedó tan tranquila'
"Me dijo 'te odio' y se quedó tan tranquila"
'Me dijo \'te odio\' y se quedó tan tranquila'
"Me dijo \"te odio\" y se quedó tan tranquila"
"""Me dijo "te odio" y se quedó tan tranquila"""

"""Método **casefold**: proporciona una versión de la cadena susceptible de ser comparada con otra sin tener en cuenta las mayúsculas o minúsculas"""

cadena_1 = 'texto'
cadena_2 = 'Texto'
mutada_1 = cadena_1.casefold()
mutada_2 = cadena_2.casefold()
print(cadena_1==cadena_2) # False
print(mutada_1==mutada_2) # True

"""Método **format**: permite dar formato a la cadena de caracteres. Ver [artículo](https://www.w3schools.com/python/ref_string_format.asp)."""

txt = "For only {price:.2f} dollars!"
print(txt.format(price = 49)) # For only 49.00 dollars!

"""Métodos **strip**, **lstrip**, **rstrip**: elimina los espacios de los dos extremos de la cadena, del extremo izquierdo o del derecho respectivamente."""

texto = '       contenido       '
print('*'+texto.strip()+'*') # *contenido*
print('*'+texto.lstrip()+'*') # *contenido       *
print('*'+texto.rstrip()+'*') # *       contenido*