# -*- coding: utf-8 -*-
"""Empleados_sucios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0NghH9VRrYnpbMshlkGqsgS1CwvALGP

- http://fpaniaguapython.github.io/datos/empleados_sucios.csv
- Limpiar la muestra, tanto para faltantes como para outliers
	- Si no se puede calcular, se elimina si afecta a la estadística.
	- Si se puede calcular, la media para esa categoría.
- Cuanto ganan en promedio todos los Ingenieros de Software (34460, 34530, 34536 )
- Cuanto ganan en promedio los de Barcelona (36585, 33375, 33775)
- Cuanto ganan todos los ingenieros de software de Madrid (886077)
- Contar cuantas personas hay de cada categoría
- Mostrar diagrama de tartas con la distribución % por categorías profesionales
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('http://fpaniaguapython.github.io/datos/empleados_sucios.csv', header=None)
df.columns = ('id', 'nombre', 'apellido', 'categoria','ciudad','salario')
df.info()

"""# Anonimizar"""

df['nombre']='Nombre'
df['apellido']='Apellido'
df.head()

"""# Detectar discrepancias en las cadenas de caracteres de ciudad"""

contador_ciudad = df['ciudad'].value_counts() # Obtenemos el contador de elementos por ciudad.
contador_ciudad # Se observan ciudades con la primera letra en minúsculas y en mayúscula

"""# Normalización de los nombres de ciudad

"""

df['ciudad'] = df['ciudad'].str.capitalize()

"""# Detectar outliers"""

# df[['salario']].plot()
#df[['salario']].boxplot(vert=False)
df.boxplot(vert=False)

plt.plot(df['salario']) # Nos ayuda a detectar visualmente los outliers

"""# Corregir outliers de salario"""

from numpy import nan
df.loc[df['salario']>100000, 'salario']=nan # Asignamos nan a los que están fuera de rango
df.info()

"""# Tratar datos faltantes"""

df = df.dropna(subset='categoria') # Eliminamos los que tienen categoría faltante
df['salario'] = df['salario'].fillna(df['salario'].mean()) # Asignamos la media
df.info()

"""- Cuanto ganan en promedio todos los Ingenieros de Software

"""

df_ingenieros = df[df['categoria']=='Ingeniero de Software']
salario_medio_ingenieros_software = df_ingenieros['salario'].mean()
salario_medio_ingenieros_software

"""- Cuanto ganan en promedio los de Barcelona

"""

df_barcelona = df[df['ciudad']=='Barcelona']
salario_medio_barcelona = df_barcelona['salario'].mean()
salario_medio_barcelona

"""- Cuanto ganan todos los ingenieros de software de Madrid (886077)

"""

df_ingenieros_software_madrid = df[(df['ciudad']=='Madrid') & (df['categoria']=='Ingeniero de Software')]
salarios_acumulados_ingenieros_software_madrid = df_ingenieros_software_madrid['salario'].sum()
salarios_acumulados_ingenieros_software_madrid

"""- Contar cuantas personas hay de cada categoría

"""

contador_categorias = df['categoria'].value_counts()
contador_categorias

"""- Mostrar diagrama de tartas con la distribución % por categorías profesionales"""

contador_categorias = df['categoria'].value_counts()
contador_categorias.plot.pie(autopct='%1.3f%%')