# -*- coding: utf-8 -*-
"""Estudio población estudiantil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kgk19gWkO0ny8_IhU3PXnbFWnfN3ccs
"""

import pandas as pd

"""Obtener el fichero de datos"""

df = pd.read_csv('http://fpaniaguapython.github.io/datos/encuesta_poblacion.csv')
df

"""Mostrar la estructura del df"""

df.info()

"""Mostrar los nombres de las columnas"""

df.columns

"""Cambiar los nombres de las columnas"""

df.columns = ['timestamp', 'nombre', 'genero', 'fecha', 'altura', 'peso', 'hijos', 'felicidad']
df.info()

"""Anonimizar los datos"""

df['nombre']='Sujeto'
df.head() # Muestra los 5 primeros registros

"""Unificar las unidades de la altura"""

df['altura']=df['altura'].str.replace(',','')
df['altura']=df['altura'].str.replace('.','')
df.head()

"""Convertir de la altura a número (porque es un str)"""

df['altura']=pd.to_numeric(df['altura'])
df.info()

"""Tratar los nulos de la columna peso"""

# df['peso'] = df['peso'].fillna(0) # Asignamos 0 a los pesos nulos
# df['peso'] = df['peso'].fillna(100) # Asignamos 100 a los pesos nulos
# df = df.dropna(subset=['peso']) # Eliminar los registros cuyos pesos sean nulos
df['peso'] = df['peso'].fillna(df['peso'].mean())
df

"""# Tratar los NaN"""

# df = df.dropna() # Eliminar todos los registros con algún campo NaN o NaD
df = df.dropna(subset=['fecha']).copy() # Eliminamos los registros con el campo fecha NaN o NaD
# df['hijos'] = df['hijos'].fillna(0) # Asignamos la mediana
df['hijos'] = df['hijos'].fillna(df['hijos'].median()) # Asignamos la mediana
df.info()

"""# Calcular el IMC"""

df['IMC']=df['peso']/((df['altura']/100)**2)
df.head()

import matplotlib.pyplot as plt
plt.plot(df['altura'])

"""# Eliminar outliers"""

df = df[df['altura'] < 250]
plt.plot(df['IMC'])

"""# Reasignar los índices"""

df.reset_index(inplace=True)
df.index

"""Obtener la media de hijos de los hombres de la colección"""

df_hombres = df[df['genero'] == 'Hombre']
media_hijos_hombres = df_hombres['hijos'].mean()
media_hijos_hombres