# -*- coding: utf-8 -*-
"""Matriculaciones por CCAA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxV2VQso4wM6NdsmGn2HNLHkuCZEdXDK

URL de origen de los datos: https://www.faconauto.com/estadisticas/matriculaciones-de-turismos/

URL fichero datos: http://fpaniaguapython.github.io/datos/CCAA-ULTIMOS-DOCE-MESES-LAPTOP-H55DSDJ2.csv

- Mes de más matriculaciones en Extremadura.
- Provincia con más matriculaciones en el mes de marzo
- Provincia con más matriculaciones en total
- Total de matriculaciones
- Diagrama de barras con los datos del mes de junio (horizontal y vertical)
- Diagrama de tartas
- Histograma por trimestres
- Diagrama de correlación entre las comunidades de Madrid y Cataluña
"""

import pandas as pd
URL = 'http://fpaniaguapython.github.io/datos/CCAA-ULTIMOS-DOCE-MESES-LAPTOP-H55DSDJ2.csv'
datos = pd.read_csv(URL, sep=';', thousands='.') # 👁️ al argumento thousands
datos.info()

datos.head()



"""## 🆑 Eliminación de la fila de Total"""

# df = datos[1:] # Eliminar haciendo slicing
df = datos.drop(0) # Eliminar haciendo drop
df.head()

"""## 👌Reasignación de nombres de columnas y eliminación de la columna comunidad"""

# df.reset_index(drop=True, inplace=True) # Reasignamos los índices numéricos?
df.index = df['comunidad'] # Reasignamos los índices con los nombres de la comunidad?
df = df.drop(columns=['comunidad']) # Eliminar la columna 'comunidad'
df.head()

"""## 🔢Conversión a número"""

# No hace falta
# df = df.apply(pd.to_numeric, errors='coerce')
# df.head()

"""### 🦉Mes de más matriculaciones en Extremadura."""

mes_max = df.loc['EXTREMADURA'].idxmax()
value_max = df.loc['EXTREMADURA'].max()
print(f'Mes:{mes_max} - Matriculaciones:{value_max}')

"""## 🍃Provincia con más matriculaciones en el mes de marzo

"""

comunidad = df['mar-26'].idxmax()
matriculaciones = df['mar-26'].max()
print(f'Comunidad:{comunidad} - Matriculaciones:{matriculaciones}')

"""## 🧮 Provincia con más matriculaciones en total

"""

df_acumulado = df.cumsum(axis=1) # axis=1 --> Incrementa por columnas
df['acumulado']=df_acumulado.max(axis=1) ## Añadimos una nueva columna 'acumulado' con la suma
max_comunidad=df[df['acumulado']==df['acumulado'].max()]
for comunidad in max_comunidad.index:
    print(comunidad)

"""## 🚗Total de matriculaciones"""

df.head()
total_matriculaciones = df['acumulado'].sum()
print(total_matriculaciones)

"""- Diagrama de barras con los datos del mes de junio (horizontal y vertical)

"""

df['jun-25'].plot.bar()

df['jun-25'].plot.barh()

"""- Diagrama de tartas"""

# Tomamos como datos los acumulados

df['acumulado'].plot.pie()

"""- Histograma por trimestres

"""

df.loc['COMUNIDAD DE MADRID'][:-1].plot.hist(bins=4)

"""- Diagrama de correlación entre las comunidades de Madrid y Cataluña"""

import matplotlib.pyplot as plt

plt.scatter(df.loc['CASTILLA Y LEON'][:-1], df.loc['CASTILLA-LA MANCHA'][:-1])
plt.show()