# -*- coding: utf-8 -*-
"""PIB Mundial Wikipedia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_lphi9REEbpW52gtuNbnZE_hON0K7jH

#### Objetivos:
- Obtener el promedio del PIB según el Banco Mundial
- Obtener el país con el PIB más alto y más bajo según la ONU
"""

import requests
from io import StringIO

import pandas as pd

URL = 'https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_por_PIB_(nominal)_per_c%C3%A1pita'
headers = { "User-Agent": "Mozilla/5.0" }

html = requests.get(URL, headers=headers).text
html_io = StringIO(html)
data_frames = pd.read_html(html_io)

for data_frame in data_frames:
    print(data_frame.info())

df = data_frames[1]

"""# Renombrar columnas"""

df.columns = ['pais','fmi-estimado','fmi-año','bm-estimado','bm-año','ONU-estimado','ONU-año']
df.info()

"""Obtener la serie del bm-estimado"""

serie_bm_estimado = df['bm-estimado']
serie_bm_estimado = serie_bm_estimado.str.replace(' ','')
serie_bm_estimado = pd.to_numeric(serie_bm_estimado, errors='coerce') # Convierte a numérico y si error --> NaN
serie_bm_estimado = serie_bm_estimado.dropna() # Eliminamos los NaN

# Promedio de todos los países según el BM
promedio_bm_estimado = serie_bm_estimado.mean()
print('Media según el Banco Mundial:',promedio_bm_estimado)

df['ONU-estimado'] = df['ONU-estimado'].str.replace(' ','')
df['ONU-estimado'] = pd.to_numeric(df['ONU-estimado'], errors='coerce') # Convierte a numérico y si error --> NaN
df = df.dropna(subset=['ONU-estimado'])

# País con el PIB más alto según el ONU
fila_max = df.loc[df['ONU-estimado'].idxmax()]
print('País con el PIB más alto según el ONU:',fila_max['pais'],'con',fila_max['ONU-estimado'],'USD')

# País con el PIB más bajo según el ONU
fila_min = df.loc[df['ONU-estimado'].idxmin()]
print('País con el PIB más bajo según el ONU:',fila_min['pais'],'con',fila_min['ONU-estimado'],'USD')

# df.head(10)